using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace Config
{
    /// <summary>
    /// will generated by tools in future, this is just a sample
    /// </summary>
    [CreateAssetMenu(fileName = "ContractConfIndex", menuName = "Config/ContractConfIndex")]
    public class ContractConfIndex : ConfIndexBase<ContractConfIndex>
    {
        [System.NonSerialized]
        private Dictionary<int, ContractConf> _Dict = null;

        [UnityEngine.SerializeField]
        private ContractConf[] _Confs;

        public Dictionary<int, ContractConf> GetData()
        {
            if (_Dict == null)
            {
                // mapper is null, construct it
                _Dict = new Dictionary<int, ContractConf>(_Confs.Length);
                for (int i = 0; i < _Confs.Length; ++i)
                {
                    _Dict.Add(_Confs[i].GetMainKey(), _Confs[i]);
                }
            }
            return _Dict;
        }

#if UNITY_EDITOR
        public void SetData(ContractConf[] confs)
        {
            _Confs = confs;
        }
#endif
    }
}
